apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bodam-backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "bodam-backend-service"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.bodam.website
      secretName: bodam-backend-tls
  rules:
    - host: api.bodam.website
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bodam-backend-service
                port:
                  number: 80
