apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: bodam-prod
spec:
  template:
    spec:
      containers:
      - name: migration
        image: registry.digitalocean.com/bodam/backend:production-02a5575b9d980cfb3d0b33ee2d919245f2483a91
        command: ["alembic", "upgrade", "head"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bodam-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bodam-secrets
              key: jwt-secret
        - name: ADMIN_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bodam-secrets
              key: admin-secret-key
        - name: TOGETHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: bodam-secrets
              key: together-api-key
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: bodam-secrets
              key: sentry-dsn
              optional: true
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 0
  parallelism: 1
