apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-queue-config
  labels:
    app: redis-queue
    component: queue
    part-of: bodam
data:
  redis.conf: |
    maxmemory 1gb
    maxmemory-policy noeviction
    appendonly yes
    appendfsync everysec
    save 3600 1
