apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-queue
  labels:
    app: redis-queue
    component: queue
    part-of: bodam
spec:
  serviceName: redis-queue-service
  replicas: 1
  selector:
    matchLabels:
      app: redis-queue
  template:
    metadata:
      labels:
        app: redis-queue
        component: queue
        part-of: bodam
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          args:
            - "redis-server"
            - "/usr/local/etc/redis/redis.conf"
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -p
                - "6379"
                - PING
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-config
          configMap:
            name: redis-queue-config
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
