apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
  namespace: default
  labels:
    app: kong
spec:
  type: ClusterIP
  selector:
    app: kong
  ports:
  - name: proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: admin
    port: 8001
    targetPort: 8001
    protocol: TCP
